### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by dhalucario** [jep-a/emm#46]
Hey, is this project still active and can be contributed to? Is there a TODO list on what has to be worked on?

**Comment by Pivius** [comment]
It is still active and can be contributed to. If you look into the Projects tab there is a todo list.
Look into the [code-style-guide](https://github.com/jep-a/emm/blob/master/code-style-guide.md) before you start a contribution.
Though it's completely fine to, you shouldn't have to make changes in existing services unless you're adding a feature to it.
If you encounter anything you're unsure of look into how other files handles something similar, otherwise feel free to ask @jep-a @s-expr or @Pivius.
